apiVersion: apps/v1
kind: Deployment
metadata:
  name: kroki-excalidraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kroki
      app.kubernetes.io/component: excalidraw
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kroki
        app.kubernetes.io/component: excalidraw
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: kroki-excalidraw
          image: yuzutech/kroki-excalidraw:0.30.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8004
          readinessProbe:
            httpGet:
              path: /
              port: 8004
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 4
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        seccompProfile:
          type: RuntimeDefault
