apiVersion: v1
kind: Service
metadata:
  name: kroki-excalidraw
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kroki
    app.kubernetes.io/component: excalidraw
  ports:
    - name: http
      port: 8004
      targetPort: 8004
      protocol: TCP
