apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: kroki
    includeSelectors: true
    includeTemplates: true

resources:
  - kroki-excalidraw-deployment.yaml
  - kroki-excalidraw-service.yaml
  - kroki-deployment.yaml
  - kroki-service.yaml
