apiVersion: v1
kind: PersistentVolume
metadata:
  name: apisix-etcd-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/apisix-etcd
