---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-github-oauth
  namespace: auth-prod
spec:
  encryptedData:
    client-id: AgA5oppGi9pUlEiVrGav+BCh2X+Av9g2wf5LBsHV4zaNs5B0+xKyzkaNY2qTsvQ+9odsAuShvbJMoLhs/aqpVWnfVKplTCuq+/HuPy9E0lNw+ENgnBiPlUXQ2G3+5NWBOTunJCZlvBEVc+pnYemOtTp/hhFEQvE7pRXfnKCFl/UfB+L2AsNM4pL53c1uby0Sxh0ae6tHwR8S94o/Up0VKgBC/nD9vAFyx2cIkb1yp6LolTAQat9xQMTlNUPWUe7AHPnPSalv2pWELaGc95r1yvI0kp3oIuUl18xW3eacaOaqQadpgaadqATJTK5R9Odqzb+YYRBs0fkFk6sArDjbyrkDzpuybCKG83l+/FUOur3s8RNrZhKBONpWVBwKEzrOYrOYMX4OSGrQIupnUKNGVz4RlGMklgzFSvnonqXXezv84aQ7F7HWpaMWgjmc35TVf2jYwZO/M9xQraF46JJifsoGK+w4A52adJLaghHePzw5GY5SZpaoiXLKmdOhldzCBeOFUwRuDc4crH1PjwBgtcu7CRbajl1Ha23YVvf+GCldSXXVZ8hiyocL1C/5FOCjDRLGpF29PC7g0JnBS3b+kdXderoUOREd4yxEOC48llrY4lanFnuekZNpxkAIaLIH4bW+zdGlxbQec+OamObMcRs7znq111zToQqnkjC1sN0vfbCpasLurmCZXjmzqA4LQbQtNRCCvfapjQ1wXBNhrgB75DfLkQ==
    client-secret: AgBGYMH9glyn9sT6sjHo4hRBt8eyzV3fqF7En8lAAYafNBKb3nF5jc9UI/hN3gIuRt0FlvVVmJEmibOnRoKajRHnoebh2MgXaZIyCsfTttJND3ckYcQst+TrNCY2HJbWk3kXu54U4QdCax8vyEpRWeQ6exewN8IpbUZR/arsl6+SK03vytTtCswpxidMfI7UIQJapknj19/gxxMDbFenFRNvZBkcGwIpXxIBbMvA6tVv6Dki7vVXIcYbheFux88w1t/yn1wPrDKSIp8YU08G7wGauaa3W/ziFRDigVt2u91toUmU8xgt/3GFSc5vChfvVRd3wydWGo+mV+E8ZVt4v+jEXNuohAFrOek273xcedHxyon6RxjAbmEjs6zQkgwHqIplcp3jE8/HtTswCBqiUjSVvrN0Jw7unNslUa1CwFFR2brObXugQgY8ZPOZPZXumceNCqId1pRcyQ2F7cOxGRLMxQfWHFMdJidcGZcG5frvkOFGeAqibywC6WPtZwc3Ajeej3Eo2l0CM2M+iBSnldFkTIQISCcYf12BPWMVm8DVhFpYIrTz+ls+RqpT9VLNCU6aK/wvZL0MQw2f2/YPhvu889lL8B3d6yJ6YQw8uK/2EYl7/wKSxRNxEsB8SAH4Pmw7BS9JRIzs00o54HAm9entNRLZeyVnjOITEUMq4Fm99xCo80r5B/GQczncmkp3tEiHsBmfErnee8tE/3SIhgsGT9XU9EI8meBJ+/9Y6/IuXNESG4gmZdOS
  template:
    metadata:
      name: keycloak-github-oauth
      namespace: auth-prod
