---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-github-oauth
  namespace: identity
spec:
  encryptedData:
    client-id: AgAK7lenhyfFDQM3qkVfViqf79cEFzTLcO31GWYZiJyrxHjQwE58rUNKHGy+d6lc7NiXHeRdPROEZ7IaeLbzn1LUn7bQXGxI00XdpYe5P63gnWQVF3eawzWmS4hDhYlDEnINJDl+oka4CqvfRJecu/OfjK6xn4QrXT5C3v50VNjJckPcqhAFYKDVR6HkCN0pT7TrSXbyWcwPcbLk0pCRDmga+HRDSIggwQ0ERcoy+3Ojg2qB88EgeeQa+WOfSv+7rFub5P9Oh3DjrTC8xRKrapaza0ef5jsmJ/A8F50fUKglsfo0ZR+vgU+aXpsmwPezF9ErNycW+KVlYxvnsWx6yjlRRAG27f4CDM5QAoZOsOT/nX3c8wS75LB2qqHDMEuU2RVbtEJSDWlQKO53X4WBmTVxoFDlaVcp1j9JNPfbsKzOM6XM+3plqhwZnH2dJeFtdfDVOcAXJ/5KOdw8s9k1z0jvotGPUP/KCjFe0mA5/GjzNl6R9skb9ND/BHUzyQc1h0YSFpuTeRLx6xV26Pz+SYd0AMYW0vuXj8c8PfeMxV9LNadd7IzI2JC/Dqt4ZI6s4Ez1XxsRzWErUt8nCloJ4MMOvSTOyCSsF8x7u8nMlwqg7oRoLNdZZbqc4JRjZELZPgP5bOD17ZV4x9/mJvX23nejcoMBGtwa5irx580Wnpnu9NdBdVY5jQSyz3/BPs5FKc3doI3tZgr0edIhxiBpxNI0d/3bBA==
    client-secret: AgAdMcS4QrI90IYOyzoMRW+tt/yxRILYFGSmA9+1vV0K+TmyV67sbvSqEPQ811i90ipGerolPL0EvrAGTJdRLBVEx5wfDqA+QBJDNJ0sYtgSwQGZzRGud+nfb/1QkT3T/f8rVLBB7JET5kDN9wznlzpGp9TxDalf0kg+uSKysVGO1JyzhvvPYf4VBJ/SF7ahq9uGWDm5JTUG6O55SkDy+3cUy2b5X59+WuIvUOzLx8O3tyFFeXwQ61xZk06XmrxwhHFF6Uv22dFOZds5cLsuwj1i4STkBF9sooYS4PYgynJ5O+rvA/aDkzTI8PUodf3U6ECB2P6yI/f+Ero1Qz4rZhotsmRm/06S/VTCYJfuiOHZip74qgTqesvwrN6oNUZFdYu/WXmNxhEG+aQaTX3UdNWqi3dZ6XmD5yPVSxFS5NN/JStynr0F5UwROj/RPtJzUVePw8fIpCJ/CyNIxJZBkEg2809TgZhgMELJLbCNf80RVjKeG0zdtRQ9KQ8D74DqHt4LcBnvQTafwuueY8f+m8Sb42uzl1tqHbO6PVCok4TOhrqqi8goQkBbBbxNQzEnHTO6NhxlZvEhuK7voxjAJV7h/+ZG3dQW+4OhEL8poebFhMbBzJM3KZjC5+VJnolcKX8sKR/YK3QMiFEVk+mfkh5w3D0vhCnVlmwV28TcAW/fFs2QSp8OXJ0xcMbSkIkjHtHZPPltJSpmjnK8MiS1bdu1JMrFeYzoDujbdBcVLy/FYEAwysTmLwLc
  template:
    metadata:
      name: keycloak-github-oauth
      namespace: identity
