---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-github-oauth
  namespace: identity
spec:
  encryptedData:
    client-id: AgC2RVXqpaa4gUeg0/6YYloHhffY0T/1cw2+0hiFuAbmemzPi0GzIDl+X8uPmEWIM3rh9K8YU5gbZPLpUVwTQtZKi8lN5Q0kkjomc4DbFKphgDKc9eepjb2yurdxgXK/xVFVel9j0eLytiW8hkUUSxttVrIT399QEbGGiysGlXdK91e5wDBwnFWUC4hnvikqJO2RKSJTB6cHdEEwZAVTFdD+WeuADcbdEoiDHI3G3q2yRcy97+ZVQBP+El2EgS0hLCuCrMGixCJmdOsVJac9BVEtX94/0l3FSPSqK2czklW6SwaWlG1IphVChYpHIOolW/iKBXTiYurX8SuGt3pyoNib7UkbHsHZQXQfWQ1zYXiMf4D21oQw7vm1V8wlEsF71Mk5o/+pvFxp3MIq0WPlev9lflXGuAmTboIaPinZELB8xyyvfq0yXxrYZRMiiQdgaQWcZ9PwrkPjhSzDEiV4GbWkdOOeQXFOMWJyoGiezrV+RHsGFVN1qcZLiXztSTOsjPL44lSbBdcOzDpu2YK0QY4Hm0eazBBHu1VXGP7OEacye5wNJtundC3m3E5rQebKNjJoveM3SYaUnW22LFKgNbF79JqaWLP8EqJlyoUZlkDW+Er17WZ53RNsffy/MFbkWvkjjd6Dw6R/5e4rv9ninWvc61X/u28a60RQCPC6KhC7Iv8sCxohXpqz0/+qZgMdpwNSkE5lxPeivhU17uEPx/dT+278sw==
    client-secret: AgC7hI8rOke04AYF8V8jgEZ4pOP48udSidCCtkGE54C5RLZFJizLQbpkG/08PwcyXCw4deIEkLH9RLk9ci7SAhTyjeaCsESV5GU/xH7NsCXZdtkPQvzHh4bHQr/P/s9nwUJX6suVzCaFw7irm1m7Z28TcPqaiHCJpzVXLPHfP/tCzitJAAqAMyqOw8u1ySN/0FKczWN42yOEqdVx9PHNgInEvpyK7KJeRx+Aue+5wPP7X5GwNTWDvCz2K/E4MAkUpIgFwUsjqbk00ypul2i+F8uqRC0Iax/Wk0GD2fW4E32ELeFrcYXe5ASXnFMhryjjAkIW5kYzRMlWy4lWwMAZFjLvbPQtjVtoiGCIGIWHXUEdwD81zWRKoVfoGg4nmtG9RLjPinqRBujMhIPo/vAAXSub1VGvp4oxTWVR9as880MYkrC1YP2JS0U0lEQTmegkPGKMIrQR4mmf0CqnMZbpfUFbhL1ewDM/fQRf0zvrI+cluNygV9Lo6echCxwmMa12TlrWBjwpyY9CLl+YoSrwHXw7czTdC4WPZc4R4k7FZoZjqJFQTK0CrVwbQRRMvYddOcrVCmEzemrFPZlW1AzorjCjEGFBnwemyAyxlVKmnoIMLy4CLVvwGlHH9SqVuMA+P6lCT9bI3oXEW4SsD89eNi4tRDVD73X1kvTn5e8M8nqniLqgRo1qxOg6gNAoToE6/eb+ogXuxMZ7pMB8/mZfB0XTq2U/d1+uWYCA/AgeSHUuZ54B5G6jxTrh
  template:
    metadata:
      name: keycloak-github-oauth
      namespace: identity
