apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-github-oauth
  namespace: auth-prod
spec:
  encryptedData:
    client-id: REPLACE_WITH_SEALED_CLIENT_ID
    client-secret: REPLACE_WITH_SEALED_CLIENT_SECRET
  template:
    metadata:
      name: keycloak-github-oauth
      namespace: auth-prod
