apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps-dev

resources:
  - ../../base
  - ingress.yaml

images:
  - name: DUMMY_APP_IMAGE
    newName: DUMMY_APP_IMAGE
    newTag: DUMMY_APP_IMAGE_TAG
