apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
images:
- name: ghcr.io/ani2fun/synapse-likec4
  newName: ghcr.io/ani2fun/synapse-likec4
  newTag: ea7ca810f2f33b71bfd5f2220f8156164c88243d
