apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
images:
- name: ghcr.io/ani2fun/synapse-likec4
  newName: ghcr.io/ani2fun/synapse-likec4
  newTag: fe4764e99f5178596b68d9592adc8717cbbc6af9
