apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
images:
- name: ghcr.io/ani2fun/synapse-likec4
  newName: ghcr.io/ani2fun/synapse-likec4
  newTag: b287eeb3bc35853796e937703dad1fc6224f4323
