apiVersion: v1
kind: Service
metadata:
  name: dsa-tracker-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dsa-tracker
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
