apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - redis.yaml
  - mongo.yaml
  - code-runner.yaml
  - networkpolicy-piston.yaml
  - networkpolicy-code-runner.yaml
  - networkpolicy-likec4.yaml
