apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
- ingress.yaml
- sealedsecret.yaml
patches:
- patch: "- op: replace\n  path: /spec/replicas\n  value: 2"
  target:
    kind: Deployment
    name: cortex
images:
- name: ghcr.io/ani2fun/cortex
  newName: ghcr.io/ani2fun/cortex
  newTag: ad7bd075f874ad39aa3ebe186fc0b244e8bbd81f
