---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cortex-db
  namespace: apps-prod
spec:
  encryptedData:
    postgres-password: AgDkkDvefxmK+nXwwp5yzNg4kZkLJSFMNzRvHkGjQwFEPWCeFEloB04FHb5HIl9oNy6JR7dFMuWryPuE0/ts2EhIQrGsgeW7u19pXLFR3OHdgifcIYIK+sQTpUVomahcTKEHu9ldGn/kiF8MwJYIEPgV5FTgnb5NLC09lLsDElNkwGyZC270wiiXbeXn8RwXHTA87t6s1uDzCxcfGCR5B+EQdQPt3WNiHbrleUP0WJGKyT5ZTVwvdhk4qW8u/mJ1x/JRYk9la7XIpsYZGRyQIFhrHSHt2YCcusz+T9Q5NmeUBcm5fNzGUefaCWmqKB7VTjhpVD1pDMVLYtUBNikrKfjxszBBishXm5aoupeQwrHyEFQGUC1ASPigCK/Lw6wGvpLg4X/LvCvra18UIhUBi3wB9zELtmDDIn6luLa93Qynd7LU3yNgP5Ogo4Zb/2+2QsMmj+wCxKTFvfsIfcBQAa9K/YPWySrdfPuU8A5tw2FJ4YDra1PO5C7dxiKSdOyyry9jfuwRnIEfQwA+jZk4drW8TEXHXxLuP3P1E9gYoISTStCgnkhecx8/VCrXc5YBNuq/XemguNaZk3y88sX9zh1fxtP38o2ngf/TniMpzgF4RLPZ/hsvflwMJVjMs1+TVlqj8qZSb4YTun+YJNZWJIv3DavRubV/pgRZpGfrdq2X2LIOJkbL9EtTCa/Yu9UW+7RU5UQzxaB005fMTTexeiXCcTBAwu3gZhju2eWRSrYvoQK8VsGzV3/ZFpQ5OjoxESU=
  template:
    metadata:
      name: cortex-db
      namespace: apps-prod
