apiVersion: v1
kind: Secret
metadata:
  name: postgresql-auth
  namespace: databases-prod
type: Opaque
stringData:
  postgres-superuser-password: "SUPER_USER_PASSWORD"
  app-db-name: "appdb"
  app-db-user: "appuser"
  app-db-password: "APP_USER_PASSWORD"
