apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
- ingress.yaml
- sealedsecret.yaml
- registry-sealedsecret.yaml
patches:
- patch: "- op: replace\n  path: /spec/replicas\n  value: 2"
  target:
    kind: Deployment
    name: dsa-tracker-backend
- patch: "- op: replace\n  path: /spec/replicas\n  value: 2"
  target:
    kind: Deployment
    name: dsa-tracker-frontend
images:
- name: ani2fun/dsa-tracker-backend
  newName: ani2fun/dsa-tracker-backend
  newTag: f75181ee0c9df69c73a7dce5038532897ba58031
- name: ani2fun/dsa-tracker-frontend
  newName: ani2fun/dsa-tracker-frontend
  newTag: f75181ee0c9df69c73a7dce5038532897ba58031
