apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
- ingress.yaml
- sealedsecret.yaml
- registry-sealedsecret.yaml
patches:
- patch: "- op: replace\n  path: /spec/replicas\n  value: 2"
  target:
    kind: Deployment
    name: dsa-tracker
images:
- name: ani2fun/dsa-tracker
  newName: ani2fun/dsa-tracker
  newTag: ce908629fd5d68653394755aaa7c474755044abe
