---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dsa-tracker-regcred
  namespace: apps-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBzc/1ZqyJfbAVXw+DcwxtNCIb3OGPO/oXwhQ77MUHq/4sDHUDUcG5gmKcRCBlBkZR5pXpFicjS/i4dSumjfG+mSG87crZ5kPrMr0Km3jF7WSfZbEWboKDYdUuTLlPFwekI1mZBFLI9FAV4kilYZoPJE8xRGOdqco26ZQ9AwE+aba5FR48TscudAD2PRhnT/A2Ei++RiHJaFslT+y4NClhf9gAP692lSSOIk6OCGRCzGAFfcaOzxIxpmFzzrCWBWg8IFQwsmbS0Im+Gt2ZkOcEqRyPWlS/Hqm7Rn5i9YXAVYGvjmR2Hp9kkWkTbzzCZm9kX8jjb35rSDGQkp4QqUG2NpXR8A7qLyG4fpYLtGRFMgY4gB4zsyBCtcc0UIA1KrN6rzjQ9pS43sjqmzdbSzxe9vemjbnOmiNDb3ZF92dUvs1PA0j15EJKAfM6vvA1PwiDPbT7KAm8TTWBDMI6lWE0f2Czz1BCyUdB2DQEDK/U51qXOynarCJmhFPC8XX2gcQF55fn7Gxm0KklqXhCFphA6TN7k2KZwx/EG9aO8h9eBK2OwITUIQhcVDfP2FjvrOVLz5v3ub1ef/1TlVRKdXuRcfQyY5+PnyAGuPwXB3Gh6PNbTejojbrqiWlOy+e1rbkUBm1sUQqsioDrplIKPa0HHVxTT6DG4VQp3UN8teKs+itEORLUGaIMAiOeZouEUW+q+LsrdXo0+G8+URvrW3FEDw0p45M9FTM469fpWbbfb5qovbMvC5W2H+56qt9lJsNTARVgHRoTHdVdmvaApU0oremH07DsMWyM/iNBqDa5f6jvJc+n66GAY3OwiJNtzelyC2fVH/1blt4wDv8EnQjFYEJ401Rrpe4VlN24bkKnJAl3L5DcrwF+6UhpZ1cdVyWp5EwC95qJt1umlnSXBWWbBTLdE0MNtHlupOEiH11AoHpxVKUKLj/X/
  template:
    metadata:
      name: dsa-tracker-regcred
      namespace: apps-prod
    type: kubernetes.io/dockerconfigjson
