---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dsa-tracker-regcred
  namespace: apps-prod
spec:
  encryptedData:
    .dockerconfigjson: AgAJtE/PG+UUVyjKmuM5qE6x9T8rHmzhq0wGRfCU40zTPiv5ioCVxLfPrG6HkwHN3l0zwgIEYqiFIlD9Ahk4sRs2XAiRh342mJRCHV0kSyruxsHybAQVHxPqDm7RshXuhLyQtc3iMvTm/QQFf541lWly9j53VwYgbs/PyG32Xv6TMlRBnbIcdp6O8KK5PdJFXyHgTzsju5Y4mWzCckDU0j6zOCCiu4IC7PdPd4eD6ZVDFRzcCiy2pPIIBb/XtU6xG5HJQRVUbaR+MTbJUzPpRA++5gm2FP/SYB08qlFsFD3AcLakDBXHApqYlfk7hi60FoleH3WzcSl7WVn3jEtNTZRFCI5AqRawQGam/o5Gr+zvTehw9xQk/Pmxk9lOn/GfXwbXHIAqftMuyaaPB1HB3KhoFwKWkvevSFgbYywHQxu5duoIqJSV5v80FSU8DDmMuJqqRzzpAi0GxDOZOhV7TK1/A28TZ1E+H732WM329nMdKqZ/r1AAICGozWvCkRLBG1S0v6yGivauvnSGDwqWtKW0Xd10Hn/+evOsYe0sZfPwoZypyReU53RVv7rsV+B9/Jo7jNbAaq0EN85+nKpWYhcBNwyWQekctyH+bHWeZGKY8w35bxOQ/LDuRWkiJm0OvNQQSo2+MAc2kIr6Pt2Bxnzv+OCuVYg6jm4wl5eGdtOiRwLyK/DZvVtzh6I+x7FylQWJwXMIhC8s0a75jPe/lvmLRl/y0tDIEhet0VjFLcpaWOnGgw1JlOhuegS/6ftcfAGSE/7o4W86VQdV69A6tWyOriCfFUreAgowZBvVAODtKmM1rEfhwYKI0wLvYSZkXUmW/Uh8OFfzy6e0FQFI+d61SAKKEWGpda5KIWn8q+VbXLu321U7YylQILLUOpdZwnIcAgsno8Q4mOmmhCs4a/rb3X7RtcjPK3r+GPYa+F5NJ1HtbAJcZ2zQ
  template:
    metadata:
      name: dsa-tracker-regcred
      namespace: apps-prod
    type: kubernetes.io/dockerconfigjson
