---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dsa-tracker-db
  namespace: apps-prod
spec:
  encryptedData:
    postgres-password: AgCDbnCUx1EiYzZT4Pj7gjtbFMSIe6PnzrYcfEOv0OsjSP46TefBDWGmeJsZGisO2R4K0tXsGEqLsmq9e4tiorzDloFPKn+YIs1O+5mdm4wxRuJWV1TWVl4xDxehKkBMxBM1MSB28m1lbtFAXwCjGQXo7DYERPneBRK+IynY9K1gGw/HLrjKL8IXcsdgHdBcU5zymmUL8goh+XxNZiPWUAjp+yLgdUYGn6PFCFRkf7RVaqTpeMwTExE7Q/HWRNjLGoi5JHI5Um9oBc9/q+/gfQrPzddp5LDPV0x1SAL/N7bjs5T8N9AEmlCrHNGH7kGi9kDJ7cOniKGp/U8JrcP8k4iFMV6Lfx5FnEbyPwCkkXI3YyfD1SFMsurhU06vHlRvjaFY8zDaCHhn7Ry508eR3GItwJyIaJHXK+6NOVN6h3G4XCKjwl5vqhCwAaQFWn3rUXO4d3har87+0Z5j7/0yMVvdhrpFlNfJtomqG1+hsftp++G93dx7qJnCl1lAWQXYXFa3EyrTROpHy//w/vcQnSPoA8Izf7Ia32EPms9zo1Cza/VhYLakTqH+i9lCw4xQ7S4UaVeNHvU6/QrAgaJtx2VpM/Dbic9C/mYaz7pc0Oc39GSFEuPG7RPE/4o1z6pzjpx5t9Ej9fhrkTrLI6EcItOupVaGYcCtf0Wam/U5Gbid7anaQRGC9jevV9WP8ekgf65PoMk5gO8KGZhHM7Ta2+M6YmOzj1aM8+c=
  template:
    metadata:
      name: dsa-tracker-db
      namespace: apps-prod
