apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
- ingress.yaml
patches:
- patch: "- op: replace\n  path: /spec/replicas\n  value: 2"
  target:
    kind: Deployment
    name: notebook-app
images:
- name: ani2fun/note-book
  newName: ani2fun/note-book
  newTag: c66cee70610ecb68f2592f8672fc29a1c74b6e17
