apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
- ingress.yaml
patches:
- patch: "- op: replace\n  path: /spec/replicas\n  value: 2"
  target:
    kind: Deployment
    name: notebook-app
images:
- name: ani2fun/note-book
  newName: ani2fun/note-book
  newTag: 0f78f9f9457e6e10d6bba9c1968780a6b52a8ea0
