---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: codefolio-db
  namespace: apps-prod
spec:
  encryptedData:
    postgres-password: AgBr7QCxWHohJkVSnn/mpCMt+1InCsaF3jpqchY3bNPAz27uqmxfm4k0M71X9+uXCL4pyrteUKVj/nk/gkuv98skmqeQ4JZSqkOgUfs/w86t7Kx4NyTmNpzjP3V90xOS237tPeVtm5CuFf4uLowMb5yw4WLsmOEdBLFdg9OLzn31sjYr82GpLDuzWIzJGHe6OxWjAZhcwQa9vU1Tzk/OHcDPZs0gzIoSlxbiEaTaqOnVxxxUfG1sZ1ICfO5qNyKiVnkA9Gadk4FpdeSx5K6JLnBs0PviPSGB5Ur3S0mBP+W2F9Lp42sd/QcSAtq2lkptXXl9EDBAMstbuGzLif4OZyVX9oMSP1U80RruBv2DvSX52gi144HjPqCuomSyTzqmiQTbvnmjS8W4AjmwShnO1y8gWexbtyrmUtn3YJuSk5hVxUrrWnC9WPwLqylmmWsFAv1GmIJykMzdyVgjitHX7Z/sYkIjHYdW/zVNhNssQQTNzlGx3LZVZeeCW3m05rGUIwKHsrHKRijI9wB91Ty8hB62YceN0vxDwaPU9QDxrmnbQMGhTAlPoFn7tQ4sUb44vBRB7OZ5JHXpTaX6AuyFHroPxY+w/rNZQI7gqv0izO67usaknG99QT6FxjazKIS7lW+9hpJm09S+3ZVH8EzE3kkQrnJNy01//H0BERYjOvVBi/mZmdjHVykMkyxj6oBMnorEwhK+kU27ho0ywVSb9quiuupmOU8ghrQCkwGjIE5NPA==
  template:
    metadata:
      name: codefolio-db
      namespace: apps-prod
