apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
- ingress.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: portfolio-app
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: PISTON_URL
            value: "http://piston:2000"
    target:
      kind: Deployment
      name: portfolio-app
images:
- name: ani2fun/portfolio-app
  newName: ani2fun/portfolio-app
  newTag: 45bb3d86865b9a9c9f150f3facc285b7448fbd53
