apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps-dev

resources:
  - ../../base
  - ingress.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: PISTON_URL
            value: "http://piston.apps-prod:2000"
    target:
      kind: Deployment
      name: portfolio-app

images:
  - name: ani2fun/portfolio-app
    newName: ani2fun/portfolio-app
    newTag: 960c42375c734445d0cc07a39a471901eca81a15