apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
- ingress.yaml
images:
- name: ghcr.io/ani2fun/codefolio
  newName: ghcr.io/ani2fun/codefolio
  newTag: b7b4f364997488040a417d99e06435da4e35b346
patches:
- target:
    kind: Deployment
    name: codefolio
  patch: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: codefolio\nspec:\n\
    \  template:\n    spec:\n      nodeSelector:\n        kakde.eu/edge: \"true\"\n\
    \      tolerations:\n        - key: kakde.eu/edge\n          operator: Equal\n\
    \          value: \"true\"\n          effect: NoSchedule"
