apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
- ingress.yaml
images:
- name: ghcr.io/ani2fun/codefolio
  newName: ghcr.io/ani2fun/codefolio
  newTag: c3f94d2acd971fd27a1c77e9fa465a0b0ebc9631
