apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps-dev

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ani2fun/note-book
    newName: ani2fun/note-book
    newTag: fb6d7997036be0c601c582e353e435f498f266cc