#!/usr/bin/env bash
# Print everything you need to type into Bytebase's "Create Instance" form, for every engine.
#
#   deploy/apps/dblab/scripts/lab-credentials.sh          # passwords masked
#   deploy/apps/dblab/scripts/lab-credentials.sh --show   # passwords in full
#
# Read-only. Nothing here is stored anywhere — the lab passwords are generated by lab-up.sh and
# live only in the dblab-credentials Secret; the production one is in the sealed bytebase-db
# Secret. Default is masked so you can paste the output into a chat or an issue safely.
#
# THE HOST IS ALWAYS THE KUBERNETES SERVICE DNS NAME. Not localhost, not a node IP. Bytebase
# resolves these from inside the cluster, and getting it wrong produces a "connection refused"
# that looks exactly like a dead database.
set -euo pipefail

show=false
[ "${1:-}" = "--show" ] && show=true

command -v kubectl >/dev/null 2>&1 || { echo "kubectl not found" >&2; exit 1; }

lab()  { kubectl -n dblab    get secret dblab-credentials -o jsonpath="{.data.$1}" 2>/dev/null | base64 -d; }
prod() { kubectl -n bytebase get secret bytebase-db       -o jsonpath="{.data.$1}" 2>/dev/null | base64 -d; }

mask() {
  if [ "$show" = true ] || [ -z "${1:-}" ]; then printf '%s' "${1:-}"
  else printf '%s********%s' "$(printf %s "$1" | cut -c1-2)" "$(printf %s "$1" | tail -c 2)"; fi
}

row() { printf '  %-14s %-46s %-6s %-10s %s\n' "$1" "$2" "$3" "$4" "$5"; }

echo "=== Bytebase → Instances → Add Instance ==="
echo
printf '  %-14s %-46s %-6s %-10s %s\n' ENGINE HOST PORT USERNAME PASSWORD
printf '  %-14s %-46s %-6s %-10s %s\n' "------" "----" "----" "--------" "--------"

row "PostgreSQL" "postgresql.databases-prod.svc.cluster.local" 5432 "bytebase"  "$(mask "$(prod managed-password)")"
row "PostgreSQL" "postgres.dblab.svc.cluster.local"            5432 "$(lab postgres-user)" "$(mask "$(lab postgres-password)")"
row "MongoDB"    "mongodb.dblab.svc.cluster.local"            27017 "$(lab mongo-user)"    "$(mask "$(lab mongo-password)")"
row "Redis"      "redis.dblab.svc.cluster.local"               6379 "(blank)"   "$(mask "$(lab redis-password)")"
row "Elasticsearch" "elasticsearch.dblab.svc.cluster.local"    9200 "(blank)"   "(blank)"
row "Cassandra"  "cassandra.dblab.svc.cluster.local"           9042 "$(lab cassandra-user)" "$(lab cassandra-password)"
row "DynamoDB"   "dynamodb-local.dblab.svc.cluster.local"      8000 "dummy"     "dummy"

cat <<'NOTES'

  Per-engine extras:
    PostgreSQL (prod) — set Environment to Prod, not Test. This is the live database behind
                        Keycloak and Synapse. The `bytebase` role has full DDL+DML on granted
                        databases and is NOT a superuser; keycloak denies it reads and writes.
    MongoDB           — Authentication Database: admin
    Cassandra         — keyspace is `lab` (Bytebase takes it from the database field)
    DynamoDB          — Region: eu-central-1. Access key / secret are the username / password
                        fields; any dummy value works against DynamoDB Local.
    Elasticsearch     — no credentials at all; xpack.security is disabled in this lab.

  NOT in Bytebase (they are not databases). Reach their own UIs with:
    kubectl -n dblab port-forward svc/kafbat-ui 8081:8080     # http://localhost:8081
    kubectl -n dblab port-forward svc/rabbitmq 15672:15672    # http://localhost:15672
NOTES

if [ "$show" != true ]; then
  echo
  echo "  Passwords masked. Re-run with --show to reveal them."
fi
