apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: piston-allow-ingress-from-traefik
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: piston
      app.kubernetes.io/component: api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
        - ipBlock:
            cidr: 172.27.15.31/32
      ports:
        - protocol: TCP
          port: 2000
