---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dsa-tracker-db
  namespace: apps-dev
spec:
  encryptedData:
    postgres-password: AgCH3cy474NqjMZ2/A8LlYhrRSFAdmDbW45xz1+JKvpy/ynEGWvlywJi4hGcew3QNqNwD0zHQ6sP030J+dyuLnTw93eYyuM/NQDuFhA3QFhbKk4WPsN4D1fAJYaGTD6e+bFmYATv208TKrbaEsHnq7kInQm2T0ESwhm4njOO/ij/6iBDFEl/4Gt1wR7rCzCagYSeQkvxMwQi8gPHB6gea+rlMWp972s8t+U9NXY3AgxlFmnG3hgMmCh75UA0Q7qXvItEkGOIXQUm987r86Tp7+ZOPu6zUXgNlKhl9VGy/Tg2vvwYER8mq2BJNhgaQMghz/X9dsJapcGsE2V3TLHn8tU61UKIt9MN2xQ0IpxLBP7Pvl6sa7mGGG4W0ReKjDo/ZUQLWMq595TLwAIdK0wT2r1GWoeyskatbyEL8MKdRFpe3XSAD75ef8asr9PN6N/7wiZHMpnExcMuvGai9ywZJeO3UxjG4GKcQdw6hJP8XpwSdNelhIJbHv/OxQn+4BlDDSq/xizPLKZxEqHnlL22F4eLBqho5kjypAn7M8Su3WrEKk5/KYe7GWijj3unmNbmTOECWPBgnQ1vY8dV6PpXk/47jknoQ86TAplytN4JyvuXr/vh18aPrMpvzLk4AYGmOOMdySlzW1I6ffYVpB0FFKJxfB/2GEFQXVV0jgV1n9zub95A2/kdOr9XCmXBL1ttZU9eZg1Po9B56AUPsIztnKvTX9HkElXY/90=
  template:
    metadata:
      name: dsa-tracker-db
      namespace: apps-dev
