apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
- ingress.yaml
- sealedsecret-db.yaml
- sealedsecret-keycloak-admin.yaml
- sealedsecret-github.yaml
images:
- name: ghcr.io/ani2fun/synapse-rs
  newName: ghcr.io/ani2fun/synapse-rs
  newTag: ecf18082cbf30aa2323c8b39816969245202e890
