---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-github
  namespace: apps-prod
spec:
  encryptedData:
    token: AgBn1qgkDJ0yFO8cQjCvW39PfnbirLUefd2O6V1NczPv4FB1vvpusiZVNYlwue+9lFwWttat/gzvn7KXfMcUOq9Zh2e8j55ZV4XO/vrn4FnO065UHpC9QlVcj1CtVK0wTScbuil6bobonMMTRJqAdGjiOU235xZnMt4nuBSAWeSuVLRGyPtwzj6Lxq+abpa7bXja+DaoNb7pJ2a6yG7Zx4cmT1M200VBeVRLIikBeWE+GJLEMgoZIaxlMH3AXEkrtDEDlIvA3+Q52ZdvBntMCqpngd9WPP7tLwVX4XSX+OtPlyoJu+Ykb3/wBJtrGjK3Mk+KIvX5DzbouHFoxxFsGRZ01FGpesHikwHY+EVM8i1pOaIencaTiJDvp6HEseuo6jpR/tnIblWvmotZC82OuWr5A3Q+b+RhovCbVO+UAuzAVvw5ZJ51H+mk5M/1RyM7JaKBtCpgGuUQ2AbcI9nlIwNRmg8lIynqNEf9y22FXM5uc83yeqiCGBclWgT3V5h0V19ybJs6OmwKCb3J2Ip5G4Xtc0HrtOH2mXVeAG/WaYaVZVU1WY1aDQgfilpYIOY0GKXtwHj1UtZyibO+4nywQguGLTL+tsSlF3FGJi9kVG45EjIhi3GkbT0PLx0XYyiNhtx9t+yzvzCdhGATHEVnm0oNgN7EqAs0MbtkQPuzpu6cq+Woh4F9tO8ncxkCbt36ZNWsr3ScPlwSphz9ehFQaUFLoNlgKE8jalFBf0iwhbK6SenBcy//LZGX1dhSMMroo/0lIs7fVeTNwIOFd9BtBBYvO8nlmGumhxMnGzJM8ridqt8pkoNlNBNuEloZGI0=
  template:
    metadata:
      name: synapse-github
      namespace: apps-prod
