---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-db
  namespace: apps-prod
spec:
  encryptedData:
    postgres-password: AgCGfOJxG76jqFxTPx/Cs7Oq/ErYhZxCEfze0qpXXiJH5rXjL/klMfrWY9UTUSd0G8TmK12xAQy6WlPxHJP7DA8jzxgWFCyoWc5qtSXgCvXVTAiaRzHnSb0SzRibdr6plzMKYqnWaX8uyaGs429yYOwoWFC1eyncOxSBLLeaJsC6cg6DT5Cy9n4LIUKTFh6WVx/1NTfBriQlrNi5DyYex6bVGkKz5OQUYNH/GflqfYZFIePmGU1KDKmWI3baAndWFIDXVisInrfE5hJ19GN6oZQ+hLKTmytzwTdNgIsjcYvC0PugXv9KAM8kEbIrgI4F42if5w9IhUSSBG2iMFp9y/l+HMZw/7+awr8nchHJxVLiDEA8N8RwrN2E5+EzkE3Pp4SEtIWVvI1gGupnTGlwZBbejshDVQPBcuikfO+ajeerS/1pB78pOioTkXbEpzDmcrnmgIEsgt8VAUS8ZEBp2uORbjxWZoQ3seJ1e8Rnve9gEQuhVZIilgwFpXXCo5Ua3Qt5yJONvVPDFHNlDFcr6ERcYxn/oC+D28kZcnfmcKIODaFnzOevEwB++ONms4naYLg48Y7dnO4NH9enEhoPKqhVv7UaQOYPuDZ2KlZuGmRjkWTNfIaGjR/wT/FGvnuST0NMDNiJoFJCM5HxsPb9u1G5MCm4Ov+Ut2HYdK5I5vfNjVOqL0elf24Hd6sRXnCHKwJQz7a4cFHPnmpBHX2DZ97nTJgQuu6Hv6LflacqVVt8
  template:
    metadata:
      name: synapse-db
      namespace: apps-prod
