---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-keycloak-admin
  namespace: apps-prod
spec:
  encryptedData:
    password: AgBTCvOwX/Z8OU7ABrJudkMpN0C7k/Zlsp9B96F+9mkW2H73CU4BvXUOe4IwmuFr+ZerVLmJgzszjYi+7jYbssoFI3cUj0GqK1eE2LVCla7xqQ2vDminutPRdrUDtJtJaWQVhaORYgkmxrrOULrQj7Yl3xZelMfyrmxWFov0H00jLbLF+GenRagmSPAOw+6Rd6yr4aARVPCejsIbv3ETe1T5l+v90VdyYxe+jVKnxBLYb2uxjDY0Sc4jELQC8HZYAKUZoY67nLwqdOFJu5m5Q2glJdP8XuaNcEIwukURxz7ypY1CRH+DHuRL8xN74Z/rl6Lu0HVbjtRK5QFxO/yKjZZnZA2KXZ6mSW8mZVw5mwM50bfS5qORSdkTnZTm9nXnm3CeDRfEqqDhpJ87r4gI3xelx2ySVSiEcyGbHrF48ivvVUF+0o3iLWmaZESFqODepmJFWvt/vVQHdUrRfgv5hYJgkHOE7Z6UDfrbK1LCcPBlKbWl/n5n5sRLMI8Lf5mH7kmcm9tsSv7I+3/aJTJB3zohHPLP6kctDNDs3kYM7jV7hBbXrOVVtL0IrHQ8n1WsKSbzckWuoDDuVjVJhL/UYIU29mtAbEgcY6uhCX2ZeYnqJkHbaFmnPX8alxyDDZXI1Un4HKpiJFcEdiPR3WesyzUN6i15a8AyQF3CDTNGVzX0GXyX+mRZIbXoVAqJa35TQ5cWxfmSDLNuF2bNyRDEtypEh/7SgCKfwtuZXOorn8SZdw==
    username: AgAK30w3uNyCF8dxUy+dgh9rDzT0ILzJEcIgAvRAVtxuzJjSnxug8SjypbGyZhp5Yc1Nv10I8SKSR9xU0W/sNLLV+ieXOjaXBtt2zoxStI3Jct9XwqJaCjppeEMhYi2Ye2g1GWc/l94L78B6F3g2gn5MQmO5J/hmq2yRiobDCgs5LjSqP7EmegnohSmA4pZPq6QLtVOBnHE07+9x+xdnZ0CQDPnAKeQa6Spr9xoWpXrhD1RSsTSvXwf2F7Fb806uqu5Q7WgsGCtVVngGykhZpAKCarcVAwxYAzB+0MOW1mf6OExux88a8zJ4Vu2I0YR+Mbq8hmA5b5dWC/uOFmNpm1TYRV2c0aNKWzI6EMW5z3rlPQlJJPlazxZnzra2n6okWXnA8uOrx2kUifLJ2FiN64C4rBR/yEE3UuBCNaaqLI7jMxe5FGsaWgfgza80KAW4IXw+ywTs4KgChaj7zaE2zsF3Yj4SH1BX7nhT6Cj1h24lUSTN2quXTGb6tXloZkPVPdyhrV0NsftMImBqLFBxPYhwoAdcKaNy+RvV5Shisl5SMztOjMuATh8USnKd7FHe5qBdEPI1xgK7poHN3VOk44P6xw9TRywSMCElz2YUolJKipjNttejJYbna/EhSZwddvnjeF/wkDru0xov7tl78QpgsDzWy/ELJ76JMcKICMb02En7WJRaFC0luvrVwJZeDE1AvsCR2VcL
  template:
    metadata:
      name: synapse-keycloak-admin
      namespace: apps-prod
