---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-keycloak-admin
  namespace: apps-prod
spec:
  encryptedData:
    client-secret: AgCW2bvO1lS8Ruumd9JwwtlXKVSt1X66oJa/9kH7IyQBtkuuTZo35NGCDU37Zq4eEyjUA5PUaRspxFqQbv/Vpn1gqBNbAtZO6E0eoXqr+n4ZbY0JntOJDbq+6F88DkIhLrRl1tpuT5tqI95K2uiW/9mX/LkJ/FgL+YtfQo/J1U2Uu5vVYWfZZ7ZBiT8LMRL50VbaSnRFyxPNQgYSJi+mecr0HyGPuhWVwFNunQk9GXhXu4FPUk6dBleAFyl9DksvLIbgrzHWiBf4XFa3bzFuijyNNP3RW3pmBiYadnzBe/acoeEhAgWHagn73H+S7vYiL/Bfqf+Ii7gDvp10vny4SUuXMuceMZkpCDZ3QOEPMjC3z84wvFUbuJ0699PtVXAoKjVoRUe4NBrfZwk2geKHbC9VTRol0B+5PVt3awE46+oE6EzklLCwnn8KaIDXfJf7BwejR/ZgPWJ5aF23DF0UUEviVj5IRVkQrQllCVzSBxhNP19iIT9LTka+KzIdpgYTFj4z9jFXavMtVF7YGsfBIdoco7Dw3v7O8vjRYPpzgayUZarxySSsKOVafXdxcQ1Aez8qVf5ZCXQxxBeRXxFrm1BYvKC8EfT2v8H9KAjKapfHYCxfCX7RRYjUSwTtSfbFV0PoXw0Dyq8IDmN7BdRcotPlQn6xX450hMRR9+Nbce6rarYgERPCv+B8nq2lJ3GmvmXpOOuQf+nuWtA8Uh5YyuCVCgk8V+vB+D46DxyQf5GVCg==
  template:
    metadata:
      name: synapse-keycloak-admin
      namespace: apps-prod
