apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
images:
- name: ghcr.io/ani2fun/likec4
  newName: ghcr.io/ani2fun/likec4
  newTag: 9afe2b433406ee65f360aa82c9cb3d6396b7967a
