apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
images:
- name: ghcr.io/ani2fun/likec4
  newName: ghcr.io/ani2fun/likec4
  newTag: 6e485e2776adca0fb90ca9fc2c1f50c992269339
