apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
images:
- name: ghcr.io/ani2fun/synapse-go-judge
  newName: ghcr.io/ani2fun/synapse-go-judge
  newTag: 94195bacb6f6bb6681416f18c89b7af98233a93a
