apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
images:
- name: ghcr.io/ani2fun/synapse-go-judge
  newName: ghcr.io/ani2fun/synapse-go-judge
  newTag: 075c192de72647c8152b9d66ffc4d53e068edeb6
