apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
- sealedsecret.yaml
images:
- name: ghcr.io/ani2fun/cortex-tutor
  newName: ghcr.io/ani2fun/cortex-tutor
  newTag: 2e0783c05f351fa73cd205ea8b63367ba700a2dc
- name: ghcr.io/ani2fun/cortex-tutor-migrate
  newName: ghcr.io/ani2fun/cortex-tutor-migrate
  newTag: 2e0783c05f351fa73cd205ea8b63367ba700a2dc
