apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
- ingress.yaml
- sealedsecret.yaml
images:
- name: ghcr.io/ani2fun/cortex-tutor
  newName: ghcr.io/ani2fun/cortex-tutor
  newTag: 0eb03bdd541ba6b048d935549f34dea17af88877
- name: ghcr.io/ani2fun/cortex-tutor-migrate
  newName: ghcr.io/ani2fun/cortex-tutor-migrate
  newTag: 0eb03bdd541ba6b048d935549f34dea17af88877
