apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
- ../../base
- sealedsecret.yaml
images:
- name: ghcr.io/ani2fun/cortex-tutor
  newName: ghcr.io/ani2fun/cortex-tutor
  newTag: 2be8450d9a3a56caaddd79765580489798750561
- name: ghcr.io/ani2fun/cortex-tutor-migrate
  newName: ghcr.io/ani2fun/cortex-tutor-migrate
  newTag: 2be8450d9a3a56caaddd79765580489798750561
