---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC4wbwckYQsZuUd4Z1QKSzymWAl5uprDx05j2Ix91cYQorgvTH7xMNI42QitzQaFyOEwQEmTxtQ2b/xYweo23s+xnKfIRWxvz1kDvpUM8h5Rt1ji6zm9H1bF1XrspuEvz88HtsjZ9Jt9WQ8v6k3rn4OVJ/5vritOQQrAnQ/NxVeRKOCeOaaJtBnGlWu4xxG9yB7A26N0a4+hItttgrvsXaPRXUO45Pr3ACOzfKbB7v/zvMqRvaTgRm5r5nxzcX7A0alb7B1eH7J1irifJBCruow+OKPpzFhrxcw4cs/YKwOFBSQjF3VXFNVOukAkPdSdbMEx3eC3XnWoNpHNe8alRxG2Y4q/wLhqTuudqIU7RVMqrSJ8p23hfdJxBZyMx1ZbqlljjXzG6c3AGhWfghJl3YZOxKFHlEYfxHJxVKAhvZIBYvb9pZsgUMtfzmcwER9nQIoRco95+MzI4Nh9XTZFX28rIEOqhykx5ZPE/khWp195A60QjFyUX98lYFFGCuRjPgL+WqJONznXSgglqiY5VXaGBZQvLC2Gkep4KzXio/H30f+rDlgJJRcBOk049xAMmpGD7o6wrOafEYNK8yOMkP0Ba9RUVSV/rufh9B9RTTTKNp3eHylGvHpjKjVjb3/wiirqr2iPJoqWprou0eU/kL2jAUu13scmHQeXn2DZjejH8gM4NzdC8bauWDbL2YNZAyy3ZWQp5wxS0QtsmSkgSE=
    admin-user: AgAO8lX36KySgCh+IITMAugtQrIjJWeyVzCFQ7b/uhMYoMHmox39nCxQwbmv4244VWrgq9ud3g1FPh7psSW2p/PhwklFjlEabG3vbMgaLZEYBN2pBWHA/4JKq+Khz80rmCNyeDx/eYEAoxE3nOTTgGQyA/tIlL58BwmPDVASIBihjJPfG5bpaH1ePOV4/NPo1a43ILffU3d9OWzW1xoZaST/MnIyQR/Ju7OEEoZr53VIOjz+PUH5D3WkGGDP11fXIBDyTPK4l2yZduvSsksrAgcDA4JA2GJGYocCTVcA9SrhDluZQCCcNp8z5va17edj+dfyb3SeO8T1zdRTCycwu6EHD7UwNq9+BQbF3XZAGWdObobE3e7OG0Mmlb7R7HaqG4ZVkWhi6sIW3p8mH5Gh0C48KD3EcpbU2yquzWu9N4YmUO+YVhw3UjTaE1tEbuGn/7n+XGdjvuKdebOpBJNSwAo5tq5C6G66g/70YW6CP8isubiyNcu3gHN8rEoBM4nmSDAcJyJrvoTp0hrfHP/iq0CRLXsCATc4xiHZr1zzr83e6u/S23a+IDT+9LbcAArYNzjc4USHo4nTUvyo4o6mWoYH+t9K89fv8nPJo8nGlyQ9LUNmmvl3iryk+64aaXfaLP1RlQev+HN3uExoAlWj7Ew2EVt/wCRhK9YL6hsJKo41LaYlvtv48xFhLIaIVSDU/SNdIsOqpg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
