---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github-oauth
  namespace: monitoring
spec:
  encryptedData:
    client-id: AgAmAx2PmkT3OPWGq20l5/+PUsO1xVPELPHSiD63Tm8UOwatMAMBKP2sFxlcmoWqZsV3J/WOMuTPaDZ69qAfczt5Im+wSkwHSYDFlSVjwSn3YA9IJKhlXNBjsqFAdgAthwMB+EfoAl3ym/xrXq8WmtvZjVioiE4DVIwbnVYg6XjVinlGLpDjZfT0Viwn8cU4Kbh0Ea6momcsQgVg8KFJn2qxMG/X8e2JJCmMnKbZ1DLvdM8sWmJqEL7CsqCAUPzgULCnnyB/gca6okRCxUcWX5IRKONgP9xuzyIvgkItclSEQJG+YTLLuVjLRKh7L+LG0tUrbSZMERHFglQV4WUkaSJqACWXYASoIbJKiBBrEy4Vzstiv05RtUiLqizJH515Y31b0nW6yzIvvlqldx/GhCgfksn4ChXJ1gkYTyX+9iDuWWd04yIJPPujz7me2NSOtwguVznVjfABi/l0mArnww8/liikEvKKmPXS4tQXtOyD8NH6l6k3s+tmt690uwBQAHhbaLw9s77Ezd0b16u1FTE4cCqxxCRCXYeGeHTpZkkX/e6gHycUjLg52RvgdKqRWD3jii9Rw4YLZKML8OO25ry+QXkzQdYTu56FmEAxQiHeuToEvvuUvX2B1O2w9Wxq7Pc2M6uWDShrnZnWBrDixz//pQLJddxKQXzojkCmbaUfbzEju8yN01FkP6yi16xdmucaaAnzrYLnWYRqVOr1Lz7RPLUi4Q==
    client-secret: AgB+SmqaU4YsDgBgy3iQC/Z/6B1yB95j6xUL7ALwVNzTFwEaeVe7HUa2iDVYtTHPNx9nFIKatswAMp8gdbFw+EHlgkv7okGBhL7tzSoffnfnYXiGOrNvErcq1g1LJteu1ciIIhd0DuWrgZtiiTLv0NF0F3DGMpmzH4JO+TglOPy1V1UcSsblwRVQtdySKyCAT1TY5I7WW+eSAnk9CEimu8lYFsx4d1Ol8QRt7X303ObCjICUU7itkc1Zx9jf9PR0aYBh037dt0Urcyv82HfnEaHCdIAoHGpvIqLQmFfjhkYoEj8v6rkWiXIeZ1hpioHgmsBKDvPGDFe1ieiPsVz8XPkbvEKhUW3FkWuGLwa1UbNiL3boHL/8Wt9wJvGVDCnAjhrUYsjDrhyJpGtk4VQWM+oKLEO+uhGlioMvBnEGd774cwXDiMFKHMHRPQhEUlgiKls/HZ0bzwOTdSSQw8MaSxk9B9wx+Of7GMlcs3htfiumxS8drdlhO7At8Ugwc6uNUMt8V3HE7UNLKnC5SVI/glG4n59SzYEbWBxj8WGqDXcc+fOfpFdsRxRzACuFF5ZoM65/UyhtEO/pGT0Atkq9y1yfZWtFvj+gb3Q9hhfJh9qysJ6g6niBzuLG8O4xpTTmrVlIHxM/AkvfqOPFEejDG+sKAUI8HrltOPBjHvnPRgs1w0QEVOVquo4ktxpWli/bSfUWtGlFxWs+MUwX3C9/WuctcXjNcZux/KsJkUzWMWUDu7Ya4gop2waV
  template:
    metadata:
      name: grafana-github-oauth
      namespace: monitoring
