#!/usr/bin/env bash
# Seal the two runtime Secrets for Bytebase (deploy/apps/bytebase/base/*.yaml):
#
#   bytebase-oauth2-proxy   client-id      — always "bytebase-proxy"
#                           client-secret  — read STRAIGHT OUT OF KEYCLOAK, so it is never
#                                            copy-pasted through a terminal or a clipboard.
#                                            Keycloak generated it when the realm was imported.
#                           cookie-secret  — freshly generated here; oauth2-proxy requires
#                                            exactly 16, 24 or 32 decoded bytes.
#
#   bytebase-db             pg-url            — full PG_URL for Bytebase's OWN metadata store
#                                               (role/database bytebase_meta).
#                           managed-password  — the password of the `bytebase` role, the one
#                                               you type into the "Create Instance" form for
#                                               postgresql.databases-prod.svc.cluster.local.
#                                               No pod mounts this key; it is sealed so the
#                                               value stays recoverable later with
#                                               scripts/secrets/read-secret-value.sh.
#
# Passwords are kept URL-SAFE (the generator strips /+=) because pg-url interpolates them into
# a postgresql:// connection string, where a '@' or '/' would corrupt the URL — the same trap
# documented in seal-synapse-secrets.sh.
#
# Both passwords must ALSO exist in Postgres. Run deploy/apps/bytebase/bootstrap.sql with the
# values this script prints, or pass your own in so they match what you already created.
#
# Needs cluster access for the Sealed Secrets cert (WireGuard up, or run from ms-1).
#
# Usage:
#   scripts/secrets/seal-bytebase-secrets.sh [meta-password] [managed-password]
set -euo pipefail

META_PASSWORD="${1:-}"
MANAGED_PASSWORD="${2:-}"

realm="bytebase"
client_id="bytebase-proxy"
namespace="${KEYCLOAK_NAMESPACE:-identity}"
keycloak_target="${KEYCLOAK_TARGET:-deploy/keycloak}"
server_url="${KEYCLOAK_SERVER_URL:-http://127.0.0.1:8080}"

pg_host="postgresql.databases-prod.svc.cluster.local"
pg_port="5432"
pg_db="bytebase_meta"
pg_user="bytebase_meta"

for cmd in kubectl kubeseal openssl base64; do
  command -v "$cmd" >/dev/null 2>&1 || { echo "Missing required command: $cmd" >&2; exit 1; }
done

gen_password() { head -c 24 /dev/urandom | base64 | tr -d '/+=' | head -c 32; }

if [ -z "$META_PASSWORD" ]; then
  META_PASSWORD="$(gen_password)"
  echo "==> generated bytebase_meta password — use it in bootstrap.sql:"
  echo "    $META_PASSWORD"
fi

if [ -z "$MANAGED_PASSWORD" ]; then
  MANAGED_PASSWORD="$(gen_password)"
  echo "==> generated bytebase role password — use it in bootstrap.sql AND in the"
  echo "    Bytebase 'Create Instance' form:"
  echo "    $MANAGED_PASSWORD"
fi

# oauth2-proxy validates the DECODED length: 16, 24 or 32 bytes. 32 random bytes,
# url-safe base64 so it survives being carried in a cookie.
COOKIE_SECRET="$(openssl rand -base64 32 | tr -- '+/' '-_')"

echo "==> reading the $client_id client secret from the $realm realm"
admin_user="$(kubectl -n "$namespace" get secret keycloak-admin-secret -o jsonpath='{.data.username}' | base64 -d)"
admin_password="$(kubectl -n "$namespace" get secret keycloak-admin-secret -o jsonpath='{.data.password}' | base64 -d)"

b64() { printf '%s' "$1" | base64 | tr -d '\n'; }

CLIENT_SECRET="$(kubectl -n "$namespace" exec -i "$keycloak_target" -- /bin/sh -s -- \
  "$(b64 "$admin_user")" "$(b64 "$admin_password")" "$(b64 "$server_url")" \
  "$(b64 "$realm")" "$(b64 "$client_id")" <<'REMOTE'
set -eu
kcadm=/opt/keycloak/bin/kcadm.sh
"$kcadm" config credentials --server "$(printf %s "$3" | base64 -d)" --realm master \
  --user "$(printf %s "$1" | base64 -d)" --password "$(printf %s "$2" | base64 -d)" >/dev/null 2>&1
realm=$(printf %s "$4" | base64 -d)
client=$(printf %s "$5" | base64 -d)
id=$("$kcadm" get clients -r "$realm" -q "clientId=$client" --fields id --format csv --noquotes | head -n1)
[ -n "$id" ] || { echo "client $client not found on realm $realm" >&2; exit 1; }
"$kcadm" get "clients/$id/client-secret" -r "$realm" --fields value --format csv --noquotes | head -n1
REMOTE
)"

if [ -z "$CLIENT_SECRET" ]; then
  echo "Could not read the $client_id client secret. Is the $realm realm imported?" >&2
  exit 1
fi
echo "    got it (${#CLIENT_SECRET} chars, not printed)"

script_path="${BASH_SOURCE[0]:-$0}"
script_dir="$(cd "$(dirname "$script_path")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"

"$script_dir/rotate-generic-secret.sh" \
  bytebase \
  bytebase-oauth2-proxy \
  "$repo_root/deploy/apps/bytebase/overlays/prod/sealedsecret-oauth2-proxy.yaml" \
  "client-id=$client_id" \
  "client-secret=$CLIENT_SECRET" \
  "cookie-secret=$COOKIE_SECRET"

"$script_dir/rotate-generic-secret.sh" \
  bytebase \
  bytebase-db \
  "$repo_root/deploy/apps/bytebase/overlays/prod/sealedsecret-db.yaml" \
  "pg-url=postgresql://${pg_user}:${META_PASSWORD}@${pg_host}:${pg_port}/${pg_db}" \
  "managed-password=$MANAGED_PASSWORD"

echo
echo "Next: run deploy/apps/bytebase/bootstrap.sql with the passwords above, then"
echo "      kubectl apply -k deploy/apps/bytebase/overlays/prod"
